version: "3.9"

services:
  uvd:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: uvd:latest
    working_dir: /workspace
    volumes:
      - ..:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - http_proxy=http://127.0.0.1:7897
      - https_proxy=http://127.0.0.1:7897
      - all_proxy=socks5://127.0.0.1:7897
      - no_proxy=localhost,127.0.0.1
      - DISPLAY=${DISPLAY:-:0}
      - MUJOCO_GL=egl
      - CONDA_DEFAULT_ENV=uvd
      - PYTHONPATH=/workspace
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
    network_mode: host
    gpus: all
    shm_size: "8g"
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
